apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: grpcversioned
  namespace: default
spec:
  template:
    metadata:
      name: grpcversioned-grpc-example-second
    spec:
      containers:
        - image: lightbend/akkagrpcservice:0.1
          ports:
            - name: h2c
              containerPort: 8080
          env:
            - name: MESSAGE
              value: "Welcome from Akka GRPC"
  traffic:
  - tag: current
    revisionName: grpcversioned-grpc-example-first
    percent: 100
  - tag: latest
    latestRevision: true
    percent: 0