apiVersion: sources.knative.dev/v1alpha2
kind: ContainerSource
metadata:
  name: events-publisher-channel
spec:
  template:
    spec:
      containers:
        - image: lightbend/cloudevents:0.1
          imagePullPolicy: Always
          ports:
            - name: h2c
              containerPort: 8080
          env:
            - name: MESSAGE
              value: "Cloud events publisher with channel"
            - name: HOST
              value: "0.0.0.0"
  sink:
    ref:
      apiVersion: messaging.knative.dev/v1beta1
      kind: InMemoryChannel
      name: channel