apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: simpleeventsreciever
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: lightbend/simpleevents:0.1
          imagePullPolicy: Always
          command: ["/opt/app/bin/simple-events-reciever"]
          ports:
            - name: h2c
              containerPort: 8080
          env:
             - name: HOST
               value: "0.0.0.0"