apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eventsreciever
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: lightbend/cloudevents:0.1
          imagePullPolicy: Always
          command: ["/opt/app/bin/cloud-events-reciever"]
          ports:
            - name: h2c
              containerPort: 8080
          env:
            - name: HOST
              value: "0.0.0.0"